config:
  modelConfig:
    DataObject:
      plugins:
        snapshotHistory: true
  execute: [ SilverStripe\SnapshotAdmin\SnapshotHistoryExtension ]
models:
  SilverStripe\Security\Member:
    fields:
      firstName: true
      surname: true
enums:
  SnapshotActivityType:
    values:
      - ADDED
      - CREATED
      - DELETED
      - MODIFIED
      - PUBLISHED
      - UNPUBLISHED
      - REMOVED
