---
Name: snapshot-admin-extensions
After:
  - versionedadmincmsconfig
  - versioned-graphql
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\VersionedAdmin\Forms\HistoryViewerField:
    class: SilverStripe\SnapshotAdmin\SnapshotViewerField
  SilverStripe\VersionedAdmin\Extensions\CMSMainExtension:
    class: SilverStripe\SnapshotAdmin\CMSMainExtension
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripe\SnapshotAdmin\SnapshotPublishableExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'silverstripe/versioned-snapshot-admin:client/dist/js/bundle.js'
  extra_requirements_css:
    - 'silverstripe/versioned-snapshot-admin:client/dist/styles/bundle.css'
